"""data updates

Revision ID: 6e7b1965a5d4
Revises: a9e42742ccd2
Create Date: 2025-11-18 11:08:04.781926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e7b1965a5d4'
down_revision: Union[str, Sequence[str], None] = 'a9e42742ccd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('excel_data_id', sa.Integer(), nullable=False))
    op.add_column('data', sa.Column('section', sa.String(), nullable=True))
    op.add_column('data', sa.Column('subsection', sa.String(), nullable=True))
    op.add_column('data', sa.Column('excel_row_number', sa.Integer(), nullable=True))
    op.add_column('data', sa.Column('material_amount', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('labor_amount', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('total_unit_cost', sa.Float(), nullable=True))
    op.add_column('data', sa.Column('total_amount', sa.Float(), nullable=True))
    op.alter_column('data', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(
        'data',
        'quantity',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="quantity::double precision"
    )
    op.alter_column(
        'data',
        'material_unit_cost',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="material_unit_cost::double precision"
    )
    op.alter_column(
        'data',
        'labor_unit_cost',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="labor_unit_cost::double precision"
    )
    op.alter_column('data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'data', 'excel_data', ['excel_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.alter_column('data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('data', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('data', 'labor_unit_cost',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('data', 'material_unit_cost',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('data', 'quantity',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('data', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('data', 'total_amount')
    op.drop_column('data', 'total_unit_cost')
    op.drop_column('data', 'labor_amount')
    op.drop_column('data', 'material_amount')
    op.drop_column('data', 'excel_row_number')
    op.drop_column('data', 'subsection')
    op.drop_column('data', 'section')
    op.drop_column('data', 'excel_data_id')
    # ### end Alembic commands ###
