"""fresh reset

Revision ID: eb651e8281b9
Revises: 
Create Date: 2025-11-15 18:08:01.244307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb651e8281b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS estimate_sections CASCADE")
    op.execute("DROP TABLE IF EXISTS estimate_items CASCADE")
    op.execute("DROP TABLE IF EXISTS estimate_templates CASCADE")
    op.execute("DROP TABLE IF EXISTS estimates CASCADE")
    op.add_column('data', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'data', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'project_id')
    op.create_table('estimate_sections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('section_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subtotal_material', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('subtotal_labor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('subtotal_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estimate_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], name='estimate_sections_estimate_id_fkey'),
    sa.ForeignKeyConstraint(['template_id'], ['estimate_templates.id'], name='estimate_sections_template_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='estimate_sections_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('estimate_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', postgresql.ENUM('SF', 'EA', 'LS', 'LF', 'CY', 'SY', 'TON', 'HR', name='unittype'), autoincrement=False, nullable=True),
    sa.Column('material_unit_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('material_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('labor_unit_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('labor_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_unit_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('item_type', postgresql.ENUM('SECTION_HEADER', 'LINE_ITEM', 'SUBTOTAL', 'SUB_HEADER', name='itemtype'), autoincrement=False, nullable=True),
    sa.Column('section_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('estimate_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], name=op.f('estimate_items_estimate_id_fkey')),
    sa.ForeignKeyConstraint(['parent_id'], ['estimate_items.id'], name=op.f('estimate_items_parent_id_fkey')),
    sa.ForeignKeyConstraint(['section_id'], ['estimate_sections.id'], name=op.f('estimate_items_section_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('estimate_items_pkey'))
    )
    op.create_table('estimate_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='estimate_templates_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('estimates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('project_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('estimate_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('prepared_by', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('total_material', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_labor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['estimate_templates.id'], name=op.f('estimates_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('estimates_pkey'))
    )
    # ### end Alembic commands ###
